Spring Boot/add JWT support
IvanovYurii/online-book-store pull request #10
Opened 2023-11-20 17:55 UTC by IvanovYurii

2023-11-21 12:38 UTC, Sanderfuck requested changes

2023-11-21 12:38 UTC, Sanderfuck commented on src/main/java/ivanov/springbootintro/service/BookService.java
> +    BookDto save(CreateBookRequestDto requestDto) throws RegistrationException;
SOLID D - dependency inversion?

2023-11-21 12:38 UTC, Sanderfuck commented on src/main/java/ivanov/springbootintro/service/impl/BookServiceImpl.java
> +    public BookDto save(CreateBookRequestDto requestDto) throws RegistrationException {
Same situation

2023-11-23 15:20 UTC, olekskov approved these changes

2023-11-23 15:20 UTC, olekskov commented on src/main/java/ivanov/springbootintro/service/impl/BookServiceImpl.java
> +            throw new EntityAllReadyPresentException("Book with Isbn " + requestDto.getIsbn()
```suggestion
            throw new EntityAlreadyPresentException("Book with Isbn " + requestDto.getIsbn()

```

2023-11-23 16:06 UTC, merged