Spring Boot / Spring Boot Practice / Add Order model
IvanovYurii/online-book-store pull request #13
Opened 2023-12-04 01:32 UTC by IvanovYurii

1. Refactor code:
    - Rewrite updateBook method in BookServiceImpl. When the fields are updated, they can be null. The isbn field is checked for uniqueness
    - Private methods are moved before public
    - The Shopping Cart creation method has been moved to UserService. The Shopping Cart  is created automatically when the user registers.
    - Rewritten for Swagger all descriptions in controllers
    - Added annotation **@ Min()**  to requests for validation Long type.
2. Solution of this task:
   - Added entities:
      - Order
      - OrderItems.
   - Added scripts for creation tables:
      - orders
      - order_items
   - Added for the entities:
      - DTOs
      - mappers
      - repositories
      - services
   - Added OrderController with Implemented Order endpoints:
      - Place an order
      - Retrieve user's order history
      - Update order status
      - Retrieve all OrderItems for a specific order
      - Retrieve a specific OrderItem within an order

2023-12-04 12:56 UTC, okuzan requested changes

2023-12-04 12:56 UTC, okuzan commented on src/main/java/ivanov/springbootintro/service/impl/UserServiceImpl.java
> +    public UserResponseDto registerUser(UserRegistrationRequestDto requestDto)
```suggestion
    public UserResponseDto register(UserRegistrationRequestDto requestDto)

```

2023-12-04 12:56 UTC, okuzan commented on src/main/java/ivanov/springbootintro/service/impl/OrderServiceImpl.java
> +        );
repeated logic, encapsulate in a separate method

2023-12-04 12:56 UTC, okuzan commented on src/main/java/ivanov/springbootintro/service/impl/OrderServiceImpl.java
> +                () -> new EntityNotFoundException("Invalid status: " + request.status()));
encapsulate in a separate method

2023-12-04 12:56 UTC, okuzan commented on src/main/java/ivanov/springbootintro/service/impl/OrderServiceImpl.java
> +                .map(item -> item.getPrice().multiply(BigDecimal.valueOf(item.getQuantity())))
place private method after public ones

2023-12-04 12:56 UTC, okuzan commented on src/main/java/ivanov/springbootintro/service/BookService.java
>  public interface BookService {
previous naming was more common TBH, it's bookService, we don't need to mention "book" in every method

2023-12-04 12:59 UTC, okuzan commented on src/main/java/ivanov/springbootintro/service/impl/OrderServiceImpl.java
> +                .collect(Collectors.toSet());
you can consider refactoring to this if you want to 
```
private Set<OrderItem> createOrderItems(Order order, Set<CartItem> cartItems) {
    return cartItems.stream()
            .map(cartItem -> createOrderItemFromCartItem(order, cartItem))
            .collect(Collectors.toSet());
}

private OrderItem createOrderItemFromCartItem(Order order, CartItem cartItem) {
    OrderItem orderItem = new OrderItem();
    orderItem.setOrder(order);
    orderItem.setBook(cartItem.getBook());
    orderItem.setQuantity(cartItem.getQuantity());
    orderItem.setPrice(cartItem.getBook().getPrice());
    return orderItem;
}

```

2023-12-05 10:32 UTC, kozhukhovsky approved these changes

2023-12-05 12:08 UTC, merged