Spring Boot / Spring Boot Testing
IvanovYurii/online-book-store pull request #15
Opened 2024-01-26 18:55 UTC by IvanovYurii

1.	Changes:
    •	The book creation method (**create**) has been rewritten. Added category existence check.
    •	The book data update method (**updateById**) has been rewritten. An update request can have empty field values. Mandatory entry fields will remain unchanged, optional fields will be empty.
    •	The **getBooksByCategoryId** method has been moved from **CategoryService** to **BookService**.
    •	Import lombok.experimental.**Accessors** for entities that supported it.
    •	**BookMapper**. Added a null check to the setCategories method.
    •	Added necessary data to a**pplication.properties, pom.xml, docker-compose.yml** files.
    •	In **CategoryServiceImpl**, the logic that was repeated was moved to a separate **assertCategoryExistsById** method
    •	A default test is returned in **SpringBootIntroApplicationTests**.
2.	Fixed:
    •	Fixed error return texts in **CustomGlobalExceptionHandler**.
    •	**Category** entity field **category_description was accidentally marked as not null**. Fixed in all related files: **Category, CreateCategoryRequestDto, 10-create-categories-table.yaml**
3.	Added:
•	**UpdateBookRequestDto** for the ability to send an update request with empty fields.
•	Service level tests: **BookServiceImplTest, CategoryServiceImplTest.**
•	application.properties in the tests is configured to use the **docker container**.
•	The database folder has been added, which contains files that allow you to work with the database (create, destroy, modify tables and data) with the help of sql queries.
•	Added integration tests **BookStoreControllerIntegrationTest**, **CategoryControllerIntegrationTest**.

4. **Screenshot with the test coverage result**

![Screenshot with the test coverage result](https://github.com/IvanovYurii/online-book-store/assets/128720591/bbed3643-7c03-43b8-8d6b-76ee9ea40865)

2024-01-27 09:55 UTC, Ivan95kos requested changes
Please, fix all checks

2024-01-27 09:55 UTC, Ivan95kos commented on src/main/java/ivanov/springbootintro/mapper/BookMapper.java
> +        if (requestDto.categoryIds() != null) {
You can use the Objects.nonNull()
```suggestion
        if (Objects.nonNull(requestDto.categoryIds())) {
```

2024-01-27 09:55 UTC, Ivan95kos commented on src/main/java/ivanov/springbootintro/service/impl/BookServiceImpl.java
> +        if (requestDto.categoryIds() != null && !requestDto.categoryIds().isEmpty()) {
You can use the Objects.nonNull()

2024-01-27 09:55 UTC, Ivan95kos commented on src/main/java/ivanov/springbootintro/service/impl/BookServiceImpl.java
> +                ? requestDto.title() : book.getTitle());
You do the same twice
```suggestion
        book.setTitle(Objects.nonNull(requestDto.title()) && !requestDto.title().isEmpty()
                ? requestDto.title() : book.getTitle());
```

2024-01-27 09:55 UTC, Ivan95kos commented on src/main/java/ivanov/springbootintro/service/impl/BookServiceImpl.java
> +        book.setTitle(requestDto.title() != null && !requestDto.title().isEmpty()
It is better to move to the mapper, than to check every field here

2024-01-30 10:59 UTC, kozhukhovsky approved these changes

2024-01-30 16:15 UTC, merged